# Generated by Django 4.2.5 on 2023-10-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommersApp', '0005_product_vendor_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('process', 'Processing'), ('delivered', 'Delivered'), ('shipped', 'Shipped')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('in_review', 'In Review'), ('draft', 'Draft'), ('disabled', 'Disabled')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(2, '★★☆☆☆'), (1, '★☆☆☆☆'), (4, '★★★★☆'), (5, '★★★★★'), (3, '★★★☆☆')], default=None),
        ),
    ]
